// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npmycubsemcwfnigumol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wbXljdWJzZW1jd2ZuaWd1bW9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MTQxOTgsImV4cCI6MjA3MTE5MDE5OH0.RfLuNnYOTjr-ndfM9VhmzxG5tNZscwIE8czsRGUB-b0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});